In [2]:
import numpy as np
import random

In [3]:
eye3 = np.eye(3,3)
eye5 = np.eye(5,5)

In [4]:
rand_eye_3 = np.random.rand(3,3) # 3 x 3
print("Matrix 3x3 with random values: \n\n{}\n".format(rand_eye_3))

rand_eye_3 = np.reshape(rand_eye_3, 9) # 1 x 9
print("Same matrix, but 1x9: \n\n{}\n".format(rand_eye_3))

rand_eye_3 = np.reshape(rand_eye_3, (9,1)) # 9 x 1
print("Same matrix, but 9x1: \n\n{}\n".format(rand_eye_3))

rand_eye_3 = np.reshape(rand_eye_3, (1,3,3)) # 3 x 3 x 1
print("Same matrix, but 3x3x1: \n\n{}\n".format(rand_eye_3))

rand_eye_3 = np.reshape(rand_eye_3, (3,3)) # back to 3x3
print("Start matrix 3x3: \n\n{}".format(rand_eye_3))

Matrix 3x3 with random values: 

[[0.71212554 0.0198652  0.63234119]
 [0.77055447 0.22890606 0.35056294]
 [0.83090079 0.10071692 0.70980019]]

Same matrix, but 1x9: 

[0.71212554 0.0198652  0.63234119 0.77055447 0.22890606 0.35056294
 0.83090079 0.10071692 0.70980019]

Same matrix, but 9x1: 

[[0.71212554]
 [0.0198652 ]
 [0.63234119]
 [0.77055447]
 [0.22890606]
 [0.35056294]
 [0.83090079]
 [0.10071692]
 [0.70980019]]

Same matrix, but 3x3x1: 

[[[0.71212554 0.0198652  0.63234119]
  [0.77055447 0.22890606 0.35056294]
  [0.83090079 0.10071692 0.70980019]]]

Start matrix 3x3: 

[[0.71212554 0.0198652  0.63234119]
 [0.77055447 0.22890606 0.35056294]
 [0.83090079 0.10071692 0.70980019]]


In [5]:
eye3 = np.eye(3,3)
eye3_copy = np.eye(3,3)
np.array_equal(eye3, eye3_copy)

True

In [6]:
rande1 = np.random.rand(3,3)
rande2 = np.random.rand(3,3)

conc_matrix = np.concatenate((rande1,rande2), axis=0)
print(conc_matrix)

print("\n")

conc_matrix = np.concatenate((rande1,rande2), axis=1)
print(conc_matrix)

[[0.80887642 0.5038442  0.27379149]
 [0.3484735  0.6142462  0.52300193]
 [0.60478583 0.26496209 0.29454789]
 [0.88396401 0.38632803 0.40968326]
 [0.38642078 0.49261453 0.06226373]
 [0.83147054 0.62578873 0.62584996]]


[[0.80887642 0.5038442  0.27379149 0.88396401 0.38632803 0.40968326]
 [0.3484735  0.6142462  0.52300193 0.38642078 0.49261453 0.06226373]
 [0.60478583 0.26496209 0.29454789 0.83147054 0.62578873 0.62584996]]


In [8]:
%time np.eye(3,3)

#%time np.zeros((3,3))

def my_eye(a, b):
    count=0
    nm=np.zeros((a,b))
    m = min(a,b)
    while (count<m):
        nm[count][count]=1
        count=count+1
    return nm

%time my_eye(3,3)
#print(my_eye(4,4))
# all my functions will work faster

CPU times: user 44 µs, sys: 3 µs, total: 47 µs
Wall time: 50.8 µs
CPU times: user 12 µs, sys: 0 ns, total: 12 µs
Wall time: 16 µs


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Calculate Inverse Matrix 2x2

matrx = np.random.rand(2,2)

def invmatrx(a):
    det = a[0][0]*a[1][1]-(a[0][1]*a[1][0])
    new_A = np.zeros((2,2))
    new_A[0][0] = a[1][1]
    new_A[0][1] = -a[0][1]
    new_A[1][0] = -a[1][0]
    new_A[1][1] = a[0][0]
    new_A = 1/det * new_A
    return new_A
    
%time np.linalg.inv(matrx)

%time invmatrx(matrx)
    
print(invmatrx(matrx))

print("\n")

print(np.linalg.inv(matrx))

CPU times: user 483 µs, sys: 146 µs, total: 629 µs
Wall time: 744 µs
CPU times: user 54 µs, sys: 4 µs, total: 58 µs
Wall time: 61.3 µs
[[ 2.4499056  -3.55330674]
 [-1.40682599  3.74075134]]


[[ 2.4499056  -3.55330674]
 [-1.40682599  3.74075134]]
